spring:
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/usping
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  mail:
    host: smtp.qq.com
    username: go@usping.cn
    password: ldygdifmueyobbii
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    port: 25

server:
  tomcat:
    accesslog:
      enabled: true
      pattern: common
      directory: logs
security:
  basic:
    enabled: false

mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    org.springframework: WARN
#    com.spring.ibatis.UserMapper: DEBUG
    com.usping.kdsn.mapper.UserMapper: DEBUG
    com.usping.kdsn.mapper.CommentMapper: DEBUG
    com.usping.kdsn.mapper.TaskMapper: DEBUG
    com.usping.kdsn.mapper.MenuMapper: DEBUG
    com.usping.kdsn.mapper.TransactionMapper: DEBUG
    com.usping.kdsn.mapper.MessageMapper: DEBUG
    mapper.MessageMapper: DEBUG
debug: true
#  file: logs/spring-boot-logging.log
